# Generated by Django 2.1 on 2021-04-21 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluacion', '0002_remove_urls_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='urls',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
